In [61]:
import pandas as pd
df = pd.read_excel(r"C:\Users\gabri\OneDrive\Documentos\Data Science Projects with Python\default_of_credit_card_clients__courseware_version_1_21_19.xls")
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [62]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  

[5 rows x 25 columns]

In [63]:
df['ID'].nunique()

29687

In [64]:
df.shape

(30000, 25)

In [65]:
id_counts = df['ID'].value_counts()
id_counts.head()

cd944abe-cef9    2
27e04c06-487f    2
80282ca6-96a6    2
0a37c2c7-6065    2
ad63957b-ea9a    2
Name: ID, dtype: int64

In [66]:
id_counts.head(30)

cd944abe-cef9    2
27e04c06-487f    2
80282ca6-96a6    2
0a37c2c7-6065    2
ad63957b-ea9a    2
fa286931-8ded    2
ff8b7170-ce3a    2
5b8dce34-2ded    2
96970f37-abaa    2
4dc45e9a-27bd    2
3367c92b-b1ca    2
42009c72-651f    2
e07a0034-42af    2
73ed1381-3a3f    2
26bde6da-f148    2
2618fdc4-e731    2
87dec940-75b7    2
72598524-ef0b    2
08425e64-bf76    2
54ada30b-750f    2
d9dafe9c-b497    2
9db1809e-845a    2
f20d8a3d-d047    2
bae9475e-7cad    2
dd019fd7-f591    2
e39d23fe-aa5f    2
4fcef74d-0b3d    2
c69162db-4864    2
62608fd2-d7fb    2
1fb3e3e6-a68d    2
Name: ID, dtype: int64

In [67]:
id_counts.value_counts()

1    29374
2      313
Name: ID, dtype: int64

In [68]:
import numpy as np
from numpy.random import default_rng

In [69]:
rg = default_rng(12345)

In [70]:
random_integers = rg.integers(low=1, high=5, size=100)

In [71]:
random_integers[:5]

array([3, 1, 4, 2, 1], dtype=int64)

In [72]:
is_equal_to_3 = random_integers == 3

In [73]:
is_equal_to_3[:5]

array([ True, False, False, False, False])

In [74]:
sum(is_equal_to_3)

31

In [75]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [76]:
id_counts = df['ID'].value_counts()
id_counts.head()

cd944abe-cef9    2
27e04c06-487f    2
80282ca6-96a6    2
0a37c2c7-6065    2
ad63957b-ea9a    2
Name: ID, dtype: int64

In [77]:
dupe_mask = id_counts == 2
dupe_mask[0:5]

cd944abe-cef9    True
27e04c06-487f    True
80282ca6-96a6    True
0a37c2c7-6065    True
ad63957b-ea9a    True
Name: ID, dtype: bool

In [78]:
id_counts.index[0:5]

Index(['cd944abe-cef9', '27e04c06-487f', '80282ca6-96a6', '0a37c2c7-6065',
       'ad63957b-ea9a'],
      dtype='object')

In [79]:
dupe_ids = id_counts.index[dupe_mask]

In [80]:
dupe_ids = list(dupe_ids)
len(dupe_ids)

313

In [81]:
dupe_ids[0:5]

['cd944abe-cef9',
 '27e04c06-487f',
 '80282ca6-96a6',
 '0a37c2c7-6065',
 'ad63957b-ea9a']

In [82]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:]

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
17523  27e04c06-487f     200000    2          2         1   37     1      2   
17623  27e04c06-487f          0    0          0         0    0     0      0   
18155  80282ca6-96a6     200000    1          1         2   33     1     -1   
18255  80282ca6-96a6          0    0          0         0    0     0      0   
28608  cd944abe-cef9     140000    2          2         1   38     0      0   
28708  cd944abe-cef9          0    0          0         0    0     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
17523      0      0  ...      10155      12470      13571         0      2000   
17623      0      0  ...          0          0          0         0         0   
18155     -1     -1  ...        667        251       -165      1000       499   
18255      0      0  ...          0          0          0         0         0   
28608      2      0  ...      95736      95912      97070     18000         0   
28708      0      0  ...          0          0          0         0         0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
17523      1155      2470      1265         0                           0  
17623         0         0         0         0                           0  
18155      1000         0         0      1000                           0  
18255         0         0         0         0                           0  
28608     10000      5000      6000      6000                           0  
28708         0         0         0         0                           0  

[6 rows x 25 columns]

In [83]:
df_zero_mask = df == 0

In [84]:
df_zero_mask

ID  LIMIT_BAL    SEX  EDUCATION  MARRIAGE    AGE  PAY_1  PAY_2  \
0      False      False  False      False     False  False  False  False   
1      False      False  False      False     False  False  False  False   
2      False      False  False      False     False  False   True   True   
3      False      False  False      False     False  False   True   True   
4      False      False  False      False     False  False  False   True   
...      ...        ...    ...        ...       ...    ...    ...    ...   
29995  False      False  False      False     False  False   True   True   
29996  False      False  False      False     False  False  False  False   
29997  False      False  False      False     False  False  False  False   
29998  False      False  False      False     False  False  False  False   
29999  False      False  False      False     False  False   True   True   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0      False  False  ...       True       True       True      True     False   
1       True   True  ...      False      False      False      True     False   
2       True   True  ...      False      False      False     False     False   
3       True   True  ...      False      False      False     False     False   
4      False   True  ...      False      False      False     False     False   
...      ...    ...  ...        ...        ...        ...       ...       ...   
29995   True   True  ...      False      False      False     False     False   
29996  False  False  ...      False      False       True     False     False   
29997  False  False  ...      False      False      False      True      True   
29998   True   True  ...      False      False      False     False     False   
29999   True   True  ...      False      False      False     False     False   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0          True      True      True      True                       False  
1         False     False      True     False                       False  
2         False     False     False     False                        True  
3         False     False     False     False                        True  
4         False     False     False     False                        True  
...         ...       ...       ...       ...                         ...  
29995     False     False     False     False                        True  
29996     False     False      True      True                        True  
29997     False     False     False     False                       False  
29998     False     False     False     False                       False  
29999     False     False     False     False                       False  

[30000 rows x 25 columns]

In [85]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)

In [86]:
feature_zero_mask

0        False
1        False
2        False
3        False
4        False
         ...  
29995    False
29996    False
29997    False
29998    False
29999    False
Length: 30000, dtype: bool

In [87]:
sum(feature_zero_mask)

315

In [88]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()

In [89]:
df_clean_1.shape

(29685, 25)

In [90]:
df_clean_1['ID'].nunique()

29685

In [91]:
df_clean_1.to_csv(r'C:\Users\gabri\OneDrive\Documentos\Data Science Projects with Python\df_clean_1.csv', index=False)